# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stats_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='stats_service.proto',
  package='stats.service',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13stats_service.proto\x12\rstats.service\x1a\x1bgoogle/protobuf/empty.proto\">\n\x04Stat\x12\x10\n\x08playerId\x18\x01 \x01(\t\x12\x10\n\x08periodId\x18\x02 \x01(\t\x12\x12\n\ntotalMoney\x18\x03 \x01(\x02\"\x1f\n\x0bPeriodIdReq\x12\x10\n\x08periodId\x18\x01 \x01(\t\"1\n\x0eStatsViaPeriod\x12\x10\n\x08playerId\x18\x01 \x01(\t\x12\r\n\x05money\x18\x02 \x01(\x02\"C\n\x13StatsViaPeriodReply\x12,\n\x05stats\x18\x01 \x03(\x0b\x32\x1d.stats.service.StatsViaPeriod\"/\n\tStatReply\x12\"\n\x05stats\x18\x01 \x03(\x0b\x32\x13.stats.service.Stat2\xb3\x02\n\x05Stats\x12<\n\x07\x41\x64\x64Stat\x12\x13.stats.service.Stat\x1a\x18.stats.service.StatReply\"\x00(\x01\x12X\n\x14StatsViaActivePeriod\x12\x1a.stats.service.PeriodIdReq\x1a\".stats.service.StatsViaPeriodReply\"\x00\x12G\n\x0f\x43\x61lculatePeriod\x12\x1a.stats.service.PeriodIdReq\x1a\x16.google.protobuf.Empty\"\x00\x12I\n\x11TriggerRankUpdate\x12\x1a.stats.service.PeriodIdReq\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_STAT = _descriptor.Descriptor(
  name='Stat',
  full_name='stats.service.Stat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='playerId', full_name='stats.service.Stat.playerId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='periodId', full_name='stats.service.Stat.periodId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='totalMoney', full_name='stats.service.Stat.totalMoney', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=129,
)


_PERIODIDREQ = _descriptor.Descriptor(
  name='PeriodIdReq',
  full_name='stats.service.PeriodIdReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='periodId', full_name='stats.service.PeriodIdReq.periodId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=162,
)


_STATSVIAPERIOD = _descriptor.Descriptor(
  name='StatsViaPeriod',
  full_name='stats.service.StatsViaPeriod',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='playerId', full_name='stats.service.StatsViaPeriod.playerId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='money', full_name='stats.service.StatsViaPeriod.money', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=213,
)


_STATSVIAPERIODREPLY = _descriptor.Descriptor(
  name='StatsViaPeriodReply',
  full_name='stats.service.StatsViaPeriodReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='stats', full_name='stats.service.StatsViaPeriodReply.stats', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=282,
)


_STATREPLY = _descriptor.Descriptor(
  name='StatReply',
  full_name='stats.service.StatReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='stats', full_name='stats.service.StatReply.stats', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=284,
  serialized_end=331,
)

_STATSVIAPERIODREPLY.fields_by_name['stats'].message_type = _STATSVIAPERIOD
_STATREPLY.fields_by_name['stats'].message_type = _STAT
DESCRIPTOR.message_types_by_name['Stat'] = _STAT
DESCRIPTOR.message_types_by_name['PeriodIdReq'] = _PERIODIDREQ
DESCRIPTOR.message_types_by_name['StatsViaPeriod'] = _STATSVIAPERIOD
DESCRIPTOR.message_types_by_name['StatsViaPeriodReply'] = _STATSVIAPERIODREPLY
DESCRIPTOR.message_types_by_name['StatReply'] = _STATREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Stat = _reflection.GeneratedProtocolMessageType('Stat', (_message.Message,), {
  'DESCRIPTOR' : _STAT,
  '__module__' : 'stats_service_pb2'
  # @@protoc_insertion_point(class_scope:stats.service.Stat)
  })
_sym_db.RegisterMessage(Stat)

PeriodIdReq = _reflection.GeneratedProtocolMessageType('PeriodIdReq', (_message.Message,), {
  'DESCRIPTOR' : _PERIODIDREQ,
  '__module__' : 'stats_service_pb2'
  # @@protoc_insertion_point(class_scope:stats.service.PeriodIdReq)
  })
_sym_db.RegisterMessage(PeriodIdReq)

StatsViaPeriod = _reflection.GeneratedProtocolMessageType('StatsViaPeriod', (_message.Message,), {
  'DESCRIPTOR' : _STATSVIAPERIOD,
  '__module__' : 'stats_service_pb2'
  # @@protoc_insertion_point(class_scope:stats.service.StatsViaPeriod)
  })
_sym_db.RegisterMessage(StatsViaPeriod)

StatsViaPeriodReply = _reflection.GeneratedProtocolMessageType('StatsViaPeriodReply', (_message.Message,), {
  'DESCRIPTOR' : _STATSVIAPERIODREPLY,
  '__module__' : 'stats_service_pb2'
  # @@protoc_insertion_point(class_scope:stats.service.StatsViaPeriodReply)
  })
_sym_db.RegisterMessage(StatsViaPeriodReply)

StatReply = _reflection.GeneratedProtocolMessageType('StatReply', (_message.Message,), {
  'DESCRIPTOR' : _STATREPLY,
  '__module__' : 'stats_service_pb2'
  # @@protoc_insertion_point(class_scope:stats.service.StatReply)
  })
_sym_db.RegisterMessage(StatReply)



_STATS = _descriptor.ServiceDescriptor(
  name='Stats',
  full_name='stats.service.Stats',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=334,
  serialized_end=641,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddStat',
    full_name='stats.service.Stats.AddStat',
    index=0,
    containing_service=None,
    input_type=_STAT,
    output_type=_STATREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StatsViaActivePeriod',
    full_name='stats.service.Stats.StatsViaActivePeriod',
    index=1,
    containing_service=None,
    input_type=_PERIODIDREQ,
    output_type=_STATSVIAPERIODREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CalculatePeriod',
    full_name='stats.service.Stats.CalculatePeriod',
    index=2,
    containing_service=None,
    input_type=_PERIODIDREQ,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='TriggerRankUpdate',
    full_name='stats.service.Stats.TriggerRankUpdate',
    index=3,
    containing_service=None,
    input_type=_PERIODIDREQ,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_STATS)

DESCRIPTOR.services_by_name['Stats'] = _STATS

# @@protoc_insertion_point(module_scope)
