# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import stats_service_pb2 as stats__service__pb2


class StatsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddStat = channel.stream_unary(
                '/stats.service.Stats/AddStat',
                request_serializer=stats__service__pb2.Stat.SerializeToString,
                response_deserializer=stats__service__pb2.StatReply.FromString,
                )
        self.StatsViaActivePeriod = channel.unary_unary(
                '/stats.service.Stats/StatsViaActivePeriod',
                request_serializer=stats__service__pb2.PeriodIdReq.SerializeToString,
                response_deserializer=stats__service__pb2.StatsViaPeriodReply.FromString,
                )
        self.CalculatePeriod = channel.unary_unary(
                '/stats.service.Stats/CalculatePeriod',
                request_serializer=stats__service__pb2.PeriodIdReq.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.TriggerRankUpdate = channel.unary_unary(
                '/stats.service.Stats/TriggerRankUpdate',
                request_serializer=stats__service__pb2.PeriodIdReq.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class StatsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddStat(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StatsViaActivePeriod(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculatePeriod(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerRankUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StatsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddStat': grpc.stream_unary_rpc_method_handler(
                    servicer.AddStat,
                    request_deserializer=stats__service__pb2.Stat.FromString,
                    response_serializer=stats__service__pb2.StatReply.SerializeToString,
            ),
            'StatsViaActivePeriod': grpc.unary_unary_rpc_method_handler(
                    servicer.StatsViaActivePeriod,
                    request_deserializer=stats__service__pb2.PeriodIdReq.FromString,
                    response_serializer=stats__service__pb2.StatsViaPeriodReply.SerializeToString,
            ),
            'CalculatePeriod': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculatePeriod,
                    request_deserializer=stats__service__pb2.PeriodIdReq.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'TriggerRankUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerRankUpdate,
                    request_deserializer=stats__service__pb2.PeriodIdReq.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stats.service.Stats', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Stats(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddStat(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/stats.service.Stats/AddStat',
            stats__service__pb2.Stat.SerializeToString,
            stats__service__pb2.StatReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StatsViaActivePeriod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stats.service.Stats/StatsViaActivePeriod',
            stats__service__pb2.PeriodIdReq.SerializeToString,
            stats__service__pb2.StatsViaPeriodReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CalculatePeriod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stats.service.Stats/CalculatePeriod',
            stats__service__pb2.PeriodIdReq.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TriggerRankUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stats.service.Stats/TriggerRankUpdate',
            stats__service__pb2.PeriodIdReq.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
